[tools]
ruby = "latest"
go = "latest"
erlang = "latest"
elixir = "latest"
deno = "latest"
bun = "latest"
rebar = "latest"
python = ["3.12", "3.13"]
node = ["22", "24"]
"ubi:LostRuins/koboldcpp" = "latest"
"cargo:bacon" = "latest"
"cargo:fselect" = "latest"
"cargo:rusty-man" = "latest"
"ubi:aquaproj/aqua" = "latest"
"aqua:rust-lang/mdBook" = "latest"
java = "temurin-21"
"aqua:jqlang/jq" = "latest"
"aqua:ipfs/kubo" = "latest"
"aqua:sharkdp/numbat" = "latest"
"aqua:tldr-pages/tlrc" = "latest"
"aqua:rclone/rclone" = "latest"
"aqua:cli/cli" = "latest"
"aqua:gitleaks/gitleaks" = "latest"
"aqua:charmbracelet/freeze" = "latest"
"aqua:sigstore/cosign" = "latest"
"aqua:sharkdp/hyperfine" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:bazelbuild/bazelisk" = "latest"
"aqua:FiloSottile/age" = "latest"
"aqua:nushell/nushell" = "latest"
"aqua:zellij-org/zellij" = "latest"
"aqua:starship/starship" = "latest"
"aqua:charmbracelet/glow" = "latest"
"aqua:charmbracelet/vhs" = "latest"
"aqua:charmbracelet/gum" = "latest"
"aqua:jesseduffield/lazygit" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:sharkdp/hexyl" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:casey/just" = "latest"
"aqua:antonmedv/fx" = "latest"
"aqua:ajeetdsouza/zoxide" = "latest"
"aqua:pvolok/mprocs" = "latest"
"aqua:sxyazi/yazi" = "latest"
"aqua:jj-vcs/jj" = "latest"
"aqua:jacobdeichert/mask" = "latest"
"aqua:ducaale/xh" = "latest"
"aqua:WebAssembly/binaryen" = "latest"
"aqua:WebAssembly/wabt" = "latest"
"aqua:tinygo-org/tinygo" = "latest"
"aqua:apple/pkl" = "latest"
"aqua:golangci/golangci-lint" = "latest"
"aqua:gohugoio/hugo/hugo-extended" = "latest"
"aqua:jesseduffield/lazydocker" = "latest"
"aqua:gleam-lang/gleam" = "latest"
"aqua:cargo-bins/cargo-binstall" = "latest"
"aqua:itchyny/gojq" = "latest"
"aqua:jdx/hk" = "latest"
"aqua:marp-team/marp-cli" = "latest"
"aqua:Automattic/harper/harper-cli" = "latest"
"aqua:jdx/usage" = "latest"
"ubi:babashka/babashka" = { version = "latest", exe = "bb" }
