[tools]
ruby = "latest"
go = "latest"
erlang = "latest"
elixir = "latest"
deno = "latest"
bun = "latest"
rebar = "latest"
python = ["3.12", "3.13"]
node = ["22", "24"]
"ubi:LostRuins/koboldcpp" = "latest"
"ubi:BurntSushi/ripgrep" = { version = "latest", exe = "rg" }
"ubi:ajeetdsouza/zoxide" = "latest"
"ubi:antonmedv/fx" = "latest"
"ubi:casey/just" = "latest"
"ubi:charmbracelet/glow" = "latest"
"ubi:charmbracelet/gum" = "latest"
"ubi:charmbracelet/vhs" = "latest"
"ubi:ducaale/xh" = "latest"
"ubi:jacobdeichert/mask" = "latest"
"ubi:jesseduffield/lazygit" = "latest"
"ubi:jj-vcs/jj" = "latest"
"ubi:pvolok/mprocs" = "latest"
"ubi:sharkdp/bat" = "latest"
"ubi:sharkdp/fd" = "latest"
"ubi:sharkdp/hexyl" = "latest"
"ubi:sxyazi/yazi" = "latest"
usage = "latest"
"cargo:bacon" = "latest"
"cargo:fselect" = "latest"
"cargo:rusty-man" = "latest"
"ubi:aquaproj/aqua" = "latest"
"aqua:rust-lang/mdBook" = "latest"
hk = "latest"
java = "temurin-21"
"aqua:jqlang/jq" = "latest"
