[tools]
ruby = "latest"
go = "latest"
erlang = "latest"
elixir = "latest"
deno = "latest"
bun = "latest"
rebar = "latest"
python = ["3.13", "3.12"]
node = ["22", "24"]
"ubi:LostRuins/koboldcpp" = "latest"
"cargo:bacon" = "latest"
"cargo:fselect" = "latest"
"cargo:rusty-man" = "latest"
"ubi:aquaproj/aqua" = "latest"
"aqua:rust-lang/mdBook" = "latest"
java = "temurin-21"
"aqua:jqlang/jq" = "latest"
"aqua:ipfs/kubo" = "latest"
"aqua:sharkdp/numbat" = "latest"
"aqua:tldr-pages/tlrc" = "latest"
"aqua:rclone/rclone" = "latest"
"aqua:cli/cli" = "latest"
"aqua:gitleaks/gitleaks" = "latest"
"aqua:charmbracelet/freeze" = "latest"
"aqua:sigstore/cosign" = "latest"
"aqua:sharkdp/hyperfine" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:bazelbuild/bazelisk" = "latest"
"aqua:FiloSottile/age" = "latest"
"aqua:nushell/nushell" = "latest"
"aqua:zellij-org/zellij" = "latest"
"aqua:starship/starship" = "latest"
"aqua:charmbracelet/glow" = "latest"
"aqua:charmbracelet/vhs" = "latest"
"aqua:charmbracelet/gum" = "latest"
"aqua:jesseduffield/lazygit" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:sharkdp/hexyl" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:casey/just" = "latest"
"aqua:antonmedv/fx" = "latest"
"aqua:ajeetdsouza/zoxide" = "latest"
"aqua:pvolok/mprocs" = "latest"
"aqua:sxyazi/yazi" = "latest"
"aqua:jj-vcs/jj" = "latest"
"aqua:jacobdeichert/mask" = "latest"
"aqua:ducaale/xh" = "latest"
"aqua:WebAssembly/binaryen" = "latest"
"aqua:WebAssembly/wabt" = "latest"
"aqua:tinygo-org/tinygo" = "latest"
"aqua:apple/pkl" = "latest"
"aqua:golangci/golangci-lint" = "latest"
"aqua:gohugoio/hugo/hugo-extended" = "latest"
"aqua:jesseduffield/lazydocker" = "latest"
"aqua:gleam-lang/gleam" = "latest"
"aqua:cargo-bins/cargo-binstall" = "latest"
"aqua:itchyny/gojq" = "latest"
"aqua:jdx/hk" = "latest"
"aqua:marp-team/marp-cli" = "latest"
"aqua:Automattic/harper/harper-cli" = "latest"
"aqua:jdx/usage" = "latest"
"ubi:babashka/babashka" = { version = "latest", exe = "bb" }
"aqua:chmln/sd" = "latest"
"pipx:httpie" = "latest"
"pipx:visidata" = "latest"
"pipx:litecli" = "latest"
"pipx:magic-wormhole" = "latest"
"pipx:cookiecutter" = "latest"
"pipx:asciinema" = "latest"
"pipx:mkdocs" = "latest"
"pipx:ruff" = "latest"
"pipx:sphinx" = "latest"
"pipx:hy" = "latest"
"pipx:memray" = "latest"
"pipx:llm" = "latest"
"pipx:protobuf-inspector" = "latest"
"pipx:pytest" = "latest"
"pipx:doc2dash" = "latest"
"pipx:qrcode" = { version = "latest", pil = "" }
"pipx:csvkit" = { version = "latest", extras = "zstandard" }
"pipx:xonsh" = { version = "latest", extras = "full" }
"aqua:lycheeverse/lychee" = "latest"
"aqua:duckdb/duckdb" = "latest"
"aqua:ktr0731/evans" = "latest"
"cargo:uiua" = { version = "latest", features = "full" }
"aqua:joerdav/xc" = "latest"
"aqua:Lifailon/lazyjournal" = "latest"
"aqua:helix-editor/helix" = "latest"
"aqua:bufbuild/buf" = "latest"
"aqua:protocolbuffers/protobuf/protoc" = "latest"
"aqua:protocolbuffers/protobuf-go/protoc-gen-go" = "latest"
"aqua:restic/restic" = "latest"
"aqua:typst/typst" = "latest"
"aqua:aduros/wasm4" = "latest"
"aqua:bytecodealliance/wasmtime" = "latest"
"aqua:wasmerio/wasmer" = "latest"
"aqua:vi/websocat" = "latest"
"aqua:jedisct1/minisign" = "latest"
"aqua:ollama/ollama" = "latest"
"aqua:goreleaser/goreleaser" = "latest"
"aqua:neovim/neovim" = "latest"
"aqua:TomWright/dasel" = "latest"
"aqua:tailwindlabs/tailwindcss" = "latest"
"aqua:linebender/resvg" = "latest"
"pipx:pgcli" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
