" Disable the toolbar.
set guioptions-=T

" Set fonts. The sizes are slightly different on Windows, due to a different
" rendering engine.
if (has("win32") > 0) || (has("win64") > 0)
    "set gfn=DejaVu\ Sans\ Mono:h9
    set gfn=DejaVu_Sans_Mono_for_Powerline:h9:cANSI
else
    set gfn=DejaVu\ Sans\ Mono\ 9
endif

