function() {
    # Path reset
    unset PATH
    export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games

    # Default shell config, maybe
    function() {
        local profile
        if [ -d /etc/profile.d/ ] ; then
            for profile in /etc/profile.d/*.sh; do
                [ -r "$profile" ] && . "$profile"
            done
        fi
    }

    # Load the important stuff
    for script in "env" "aliases"
    do
        source $DOTFILES/zsh/$script.zsh
    done
}
