# Load our utility loading function.
. $DOTFILES/zsh/load

if [ -d /etc/profile.d/ ] ; then
    for profile in /etc/profile.d/*.sh; do
        [ -r "$profile" ] && . "$profile"
    done
    unset profile
fi

# Order matters here. 'config' can depend on variables set in 'env', and
# 'aliases' is last to avoid conflicting.
for script in "env" "config" "aliases"
do
    _tomku_load $DOTFILES/zsh/$script.zsh
done
