;; I suppose I should leave this here, Emacs gets angry when I don't...
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(abbrev-file-name (concat shared-config-dir "abbrev_defs"))
 '(abbrev-mode nil t)
 '(auto-compression-mode t)
 '(auto-image-file-mode t)
 '(backup-directory-alist (list (cons "." (concat local-config-dir "backups"))))
 '(bookmark-default-file (concat local-config-dir "emacs.bmk"))
 '(c-basic-offset 4)
 '(c-default-style (quote ((c-mode . "bsd") (c++-mode . "bsd") (java-mode . "java") (awk-mode . "awk") (other . "bsd"))))
 '(case-fold-search t)
 '(clean-buffer-list-kill-never-regexps (quote ("^ \\*Minibuf-.*\\*$" "\\.org$")))
 '(coffee-tab-width 2)
 '(column-number-mode t)
 '(comint-scroll-to-bottom-on-input (quote this))
 '(compilation-error-screen-columns t)
 '(compilation-scroll-output nil)
 '(compilation-window-height nil)
 '(compile-auto-highlight nil)
 '(compile-command "make")
 '(cperl-electric-parens t)
 '(cperl-extra-perl-args "-w")
 '(cperl-font-lock t)
 '(cperl-hairy t)
 '(cperl-indent-level 4)
 '(cperl-invalid-face (quote none))
 '(current-language-environment "English")
 '(custom-safe-themes (quote ("8aebf25556399b58091e533e455dd50a6a9cba958cc4ebb0aab175863c25b9a4" "36a309985a0f9ed1a0c3a69625802f87dee940767c9e200b89cdebdb737e5b29" default)))
 '(display-time-mode t)
 '(echo-keystrokes 0.1)
 '(ede-project-placeholder-cache-file (concat local-config-dir "projects.ede"))
 '(ediff-window-setup-function (quote ediff-setup-windows-plain))
 '(eshell-directory-name (concat local-config-dir ".eshell/"))
 '(ffap-file-finder (quote find-file))
 '(flyspell-abbrev-p t)
 '(flyspell-use-global-abbrev-table-p t)
 '(flyspell-use-meta-tab nil)
 '(global-font-lock-mode t)
 '(gnus-select-method (quote (nntp "news.gmane.org")))
 '(haskell-mode-hook (quote (turn-on-haskell-indent turn-on-haskell-indentation turn-on-haskell-doc-mode turn-on-haskell-decl-scan)) t)
 '(ido-create-new-buffer (quote always))
 '(ido-enable-dot-prefix t)
 '(ido-enable-flex-matching t)
 '(ido-enable-last-directory-history nil)
 '(ido-enabled (quote (quote both)) t)
 '(ido-everywhere t)
 '(ido-max-dir-file-cache 0)
 '(ido-mode (quote both) nil (ido))
 '(ido-save-directory-list-file (concat local-config-dir "ido.last"))
 '(ido-show-dot-for-dired t)
 '(ido-use-filename-at-point (quote guess))
 '(ido-use-url-at-point t)
 '(indent-tabs-mode nil)
 '(inhibit-eol-conversion nil)
 '(inhibit-startup-screen t)
 '(jit-lock-stealth-time 1)
 '(kill-whole-line t)
 '(line-number-mode t)
 '(menu-bar-mode nil)
 '(nxhtml-skip-welcome t)
 '(nxml-attribute-indent 2)
 '(nxml-child-indent 4)
 '(nxml-outline-child-indent 4)
 '(nxml-slash-auto-complete-flag t)
 '(org-catch-invisible-edits (quote smart))
 '(org-checkbox-hierarchical-statistics nil)
 '(org-hierarchical-checkbox-statistics nil)
 '(org-hierarchical-todo-statistics nil)
 '(org-refile-targets (quote ((org-agenda-files :maxlevel . 3))))
 '(org-refile-use-outline-path (quote file))
 '(pc-selection-mode t)
 '(preview-gs-options (quote ("-q" "-dNOPAUSE" "-DNOPLATFONTS" "-dPrinted" "-dTextAlphaBits=4" "-dGraphicsAlphaBits=4")))
 '(python-command "python")
 '(python-python-command "python")
 '(quack-programs (quote ("mzscheme" "bigloo" "csi" "csi -hygienic" "gosh" "gracket" "gsi" "gsi ~~/syntax-case.scm -" "guile" "kawa" "mit-scheme" "racket" "racket -il typed/racket" "rs" "scheme" "scheme48" "scsh" "sisc" "stklos" "sxi")))
 '(quack-smart-open-paren-p nil)
 '(recentf-save-file (concat local-config-dir ".recentf"))
 '(rng-schema-locating-files (quote ("schemas.xml" "/usr/share/emacs/23.1/etc/schema/schemas.xml" "/home/tom/.emacs.d/rnc/html5/html5-schemas.xml")))
 '(save-place t nil (saveplace))
 '(save-place-file (concat local-config-dir "emacs-places"))
 '(scroll-bar-mode (quote right))
 '(semanticdb-default-save-directory (concat local-config-dir "cache/semanticdb") t)
 '(size-indication-mode t)
 '(slime-repl-history-file (concat local-config-dir "history/slime-history.eld"))
 '(smex-save-file (concat local-config-dir "smex.save"))
 '(srecode-map-save-file (concat local-config-dir "cache/srecode/srecode-map"))
 '(tab-width 2)
 '(temp-buffer-max-height (lambda (buffer) (/ (- (frame-height) 2) 3)))
 '(temp-buffer-resize-mode t nil (help))
 '(temporary-file-directory (concat local-config-dir "temp"))
 '(tool-bar-mode nil)
 '(transient-mark-mode t)
 '(truncate-partial-width-windows nil)
 '(uniquify-buffer-name-style (quote forward) nil (uniquify))
 '(visible-bell t)
 '(whitespace-line-column 100)
 '(whitespace-style (quote (trailing lines space-before-tab indentation space-after-tab))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 113 :width normal :foundry "outline" :family "DejaVu Sans Mono for Powerline"))))
 '(highlight ((t (:underline t))))
 '(idle-highlight ((t (:foreground "dim gray")))))

